# Generated by Django 3.2.5 on 2024-07-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='options',
        ),
        migrations.AddField(
            model_name='choice',
            name='first_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='fourth_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='second_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='choice',
            name='third_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
