# Generated by Django 3.2.5 on 2024-07-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_options_yes_or_no_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='yes_or_no_choice',
            field=models.CharField(blank=True, choices=[('Choose Answer', 'Choose Answer'), ('Yes', 'Yes'), ('No', 'No')], default='Choose Answer', max_length=100),
        ),
    ]
